/**
 * The two agent files: a map of the site, and the map with every page's prose after it.
 *
 * `/llms.txt` is the map alone, sectioned by the sidebar groups in `site-nav.ts`, one
 * line per page with the description its frontmatter carries. `/llms-full.txt` is the
 * same map followed by every page's Markdown. Both carry absolute URLs: a client is as
 * likely to have been handed the file as to have fetched it.
 */
import {
  isAuto,
  isGroup,
  isLink,
  isPage,
  NAV,
  SITE_DESCRIPTION,
  SITE_NAME,
  SITE_URL,
  type NavGroup,
  type NavItem,
} from '../site-nav';

/** A docs page, as the collection holds it. The id is the slug, empty for the front page. */
export type DocPage = { id: string; title: string; description?: string; body: string };

type Entry = { label: string; href: string; description?: string; page?: DocPage };

type Section = { label: string; entries: Entry[] };

/** What a collection entry carries of a page. */
type CollectionEntry = {
  id: string;
  body?: string | undefined;
  data: { title: string; description?: string | undefined };
};

export function pagesFrom(entries: CollectionEntry[]): DocPage[] {
  return entries.map((entry) => ({
    id: entry.id,
    title: entry.data.title,
    ...(entry.data.description === undefined ? {} : { description: entry.data.description }),
    body: entry.body ?? '',
  }));
}

/** The origin every URL is written against, the configured site or the canonical one. */
export const origin = (site?: URL | undefined): string =>
  (site?.href ?? SITE_URL).replace(/\/$/, '');

/** A page's URL. Starlight serves a docs page at its slug with a trailing slash. */
const href = (base: string, path: string): string =>
  path === '' ? `${base}/` : `${base}/${path}/`;

/**
 * The pages an autogenerated group holds: the directory's own index first, then the rest
 * by slug, which is the order Starlight lists them in.
 */
function directory(pages: DocPage[], dir: string): DocPage[] {
  const under = pages.filter((p) => p.id === dir || p.id.startsWith(`${dir}/`));
  return under.sort((a, b) => (a.id === dir ? -1 : b.id === dir ? 1 : a.id.localeCompare(b.id)));
}

function entryOf(base: string, pages: DocPage[], item: NavItem): Entry[] {
  if (isLink(item)) {
    const path = item.link.replace(/^\/|\/$/g, '');
    return [{ label: item.label, href: href(base, path), description: item.description }];
  }
  const found = isPage(item) ? pages.filter((p) => p.id === item.slug) : isAuto(item) ? directory(pages, item.directory) : [];
  return found.map((page) => ({
    label: (isPage(item) && item.label) || page.title,
    href: href(base, page.id),
    ...(page.description === undefined ? {} : { description: page.description }),
    page,
  }));
}

/**
 * One section per sidebar category. A group nested in another, as the widget categories
 * are, is a section of its own, after the section its parent's own pages make.
 */
export function sections(pages: DocPage[], base: string): Section[] {
  const walk = (group: NavGroup): Section[] => {
    const own: Entry[] = [];
    const nested: Section[] = [];
    for (const item of group.items) {
      if (isGroup(item)) nested.push(...walk(item));
      else own.push(...entryOf(base, pages, item));
    }
    return [...(own.length ? [{ label: group.label, entries: own }] : []), ...nested];
  };
  return NAV.flatMap(walk);
}

const line = (entry: Entry): string =>
  `- [${entry.label}](${entry.href})${entry.description ? `: ${entry.description}` : ''}`;

function map(pages: DocPage[], base: string): string[] {
  const lines = [
    `# ${SITE_NAME}`,
    '',
    `> ${SITE_DESCRIPTION}`,
    '',
    'Every widget page says what the widget takes, what it emits and what its keys do, and shows',
    'the widget running in both frameworks. A widget is installed from one of two shadcn',
    'registries, under the name its page is at:',
    '',
    '```sh',
    `pnpm dlx shadcn@latest add ${base}/r/react/<name>.json`,
    `pnpm dlx shadcn-svelte@latest add ${base}/r/svelte/<name>.json`,
    '```',
    '',
    `The prose of every page below, as Markdown, is at ${base}/llms-full.txt.`,
    '',
  ];
  for (const section of sections(pages, base)) {
    lines.push(`## ${section.label}`, '', ...section.entries.map(line), '');
  }
  return lines;
}

export function llmsTxt(pages: DocPage[], site?: URL | undefined): string {
  return `${map(pages, origin(site)).join('\n')}`;
}

export function llmsFullTxt(pages: DocPage[], site?: URL | undefined): string {
  const base = origin(site);
  const lines = map(pages, base);
  for (const section of sections(pages, base)) {
    for (const entry of section.entries) {
      if (!entry.page) continue;
      lines.push('---', '', `# ${entry.page.title}`, '', `Source: ${entry.href}`, '');
      const body = strip(entry.page.body);
      if (body) lines.push(body, '');
    }
  }
  return lines.join('\n');
}

/**
 * An MDX body as text: the imports and the components are dropped, the prose, the tables
 * and the code blocks are kept whole.
 *
 * Outside a fenced block, a line that starts with `<` opens a tag, and every line up to
 * the one ending in `>` goes with it. Inside a fence nothing is touched, which is what
 * keeps a Svelte or a JSX sample intact.
 */
export function strip(body: string): string {
  const out: string[] = [];
  let fence = '';
  let tag = false;
  for (const raw of body.split('\n')) {
    const text = raw.trim();
    if (fence) {
      if (text.startsWith(fence)) fence = '';
      out.push(raw);
      continue;
    }
    if (text.startsWith('```') || text.startsWith('~~~')) {
      fence = text.slice(0, 3);
      out.push(raw);
      continue;
    }
    if (tag) {
      if (text.endsWith('>')) tag = false;
      continue;
    }
    if (text.startsWith('import ') || text.startsWith('export ')) continue;
    if (text.startsWith('<')) {
      if (!text.endsWith('>')) tag = true;
      continue;
    }
    out.push(raw);
  }
  // A dropped component leaves the blank lines that framed it behind.
  return out.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}
