/**
 * The `hello` demo, React side.
 *
 * It exists to prove the harness end to end: the shadcn Button is imported through the
 * `@` alias straight out of packages/react, its classes are generated by the site's
 * Tailwind build, and the button calls the demo client.
 */
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { DemoClientProvider, useSgClient } from '../_shared/react';

function Hello() {
  const client = useSgClient();
  const [output, setOutput] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  async function loadEntityTypes() {
    setBusy(true);
    try {
      const types = await client.entityTypes();
      setOutput(types.map((t) => t.displayName).join(' · '));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="flex flex-col gap-3">
      <div className="flex flex-wrap items-center gap-2">
        <Button onClick={loadEntityTypes} disabled={busy}>
          Load entity types
        </Button>
        <Button variant="secondary">Secondary</Button>
        <Button variant="outline">Outline</Button>
        <Button variant="ghost">Ghost</Button>
        <Button variant="destructive">Destructive</Button>
      </div>
      <p className="text-muted-foreground text-sm" data-demo-output>
        {output ?? 'Nothing loaded yet.'}
      </p>
    </div>
  );
}

export default function HelloDemo() {
  return (
    <DemoClientProvider>
      <Hello />
    </DemoClientProvider>
  );
}
