import type { PropsFile } from './_types';

export default {
  props: [
    { name: 'context', type: '`SgContext`', default: 'required', meaning: 'The widget context. The schema is read through it, once per page.' },
    { name: 'entityType', type: '`string`', default: 'required', meaning: 'The type every path starts on.' },
    { name: 'value', type: '`string[]`', default: '`[]`', meaning: 'The chosen dotted paths, in the order they are shown.' },
    { name: 'onValueChange', type: '`(value: string[]) => void`', default: '—', meaning: 'Receives the new array on every add, remove and move.' },
    { name: 'layout', type: '`\'list\' | \'dual\'`', default: '`\'list\'`', meaning: '`list` is the field picker over the ordered list; `dual` is the two lists side by side.' },
    { name: 'showCount', type: '`boolean`', default: '`false`', meaning: 'Show how many columns are chosen under the list.' },
    { name: 'deepLinks', type: '`boolean`', default: '`true`', meaning: 'Allow descending through entity fields.' },
    { name: 'maxDepth', type: '`number`', default: '`2`', meaning: 'How many hops a path may take.' },
    { name: 'dataTypes', type: '`string | string[]`', default: '—', meaning: 'Data types a field must have to be selected.' },
    { name: 'validTypes', type: '`string[]`', default: '—', meaning: 'A field is selectable only if it links one of these.' },
    { name: 'exclude', type: '`string[]`', default: '—', meaning: 'Full dotted paths to drop.' },
    { name: 'hidePaths', type: '`string[]`', default: '—', meaning: 'Dotted prefixes to drop, along with everything beneath them.' },
    { name: 'filterableOnly', type: '`boolean`', default: '`false`', meaning: 'Drop the data types the API refuses in a filter.' },
    { name: 'extraFields', type: '`{ name, displayName? }[]`', default: '—', meaning: 'Synthetic entries offered at the root only.' },
    { name: 'filter', type: '`(field, path) => boolean`', default: '—', meaning: 'Your own visibility test over the schema and the candidate\'s full path.' },
    { name: 'placeholder', type: '`string`', default: '`\'Add a column\'`', meaning: 'Placeholder of the field picker.' },
    { name: 'searchPlaceholder', type: '`string`', default: '`\'Search fields…\'`', meaning: 'Shown in the search box.' },
    { name: 'emptyLabel', type: '`string`', default: '`\'Nothing chosen\'`', meaning: 'Shown while no column is chosen.' },
    { name: 'noMatchLabel', type: '`string`', default: '`\'No match\'`', meaning: 'Shown when the search over the fields on offer matches nothing.' },
    { name: 'loadingLabel', type: '`string`', default: '`\'Loading…\'`', meaning: 'Names the skeletons a read stands behind, for a screen reader.' },
    { name: 'errorLabel', type: '`string`', default: '—', meaning: 'Shown in place of what the failed read said.' },
    { name: 'availableLabel', type: '`string`', default: '`\'Available\'`', meaning: 'Heading of the left list, `dual` only.' },
    { name: 'chosenLabel', type: '`string`', default: '`\'Columns\'`', meaning: 'Heading of the right list, `dual` only.' },
    { name: 'readonly', type: '`boolean`', default: '`false`', meaning: 'Shows the chosen list alone, with no controls.' },
    { name: 'disabled', type: '`boolean`', default: '`false`' },
    { name: 'invalid', type: '`boolean`', default: '`false`', meaning: 'Puts the invalid ring on the field picker, or on both lists under `dual`.' },
    { name: 'size', type: '`\'sm\' | \'md\' | \'lg\'`', default: '`\'md\'`', meaning: 'Row height.' },
    { name: 'className / class', type: '`string`', default: '—', meaning: 'Merged after the widget\'s own classes.' },
  ],
  events: [
    { name: 'onValueChange', payload: '`string[]`', when: 'A column is added, removed or moved.' },
  ],
  keyboard: [
    { key: '`Enter`, `Space` on the picker', does: 'Open the field list.' },
    { key: '`Up`, `Down`', does: 'Walk the field list.' },
    { key: '`Enter`', does: 'Add the field under the cursor. A link that cannot be chosen descends instead.' },
    { key: '`Right`', does: 'Descend into the link under the cursor.' },
    { key: '`Left`', does: 'Back one level.' },
    { key: '`Escape`', does: 'Close the field list.' },
    { key: '`Tab`', does: 'Moves through the picker, then the grip and remove button of each chosen row.' },
    { key: '`Space`, `Enter` on the grip', does: 'Picks the row up for the arrow keys.' },
    { key: '`Up`, `Down` while carrying a row', does: 'Move it one place.' },
    { key: '`Space`, `Enter` while carrying a row', does: 'Drop it where it is.' },
    { key: '`Escape` while carrying a row', does: 'Put it back where it was.' },
    { key: '`Alt` + `Up`', does: 'Move the chosen row holding focus one place earlier.' },
    { key: '`Alt` + `Down`', does: 'Move it one place later.' },
    { key: '`Delete`, `Backspace`', does: 'Remove it.' },
  ],
} satisfies PropsFile;
