import type { PropsFile } from './_types';

export default {
  extends: { name: 'collection-control' },
  props: [
    { name: 'source', type: '`EntitySource`', default: 'required', meaning: 'The rows and the paging behind them.' },
    { name: 'context', type: '`SgContext`', default: 'required', meaning: 'The widget context. Every tile reads its schema, its statuses and its links through it.' },
    { name: 'thumbnail', type: '`string | false`', default: '`\'image\'`', meaning: 'Field holding the thumbnail URL. `false` leaves every tile on the placeholder.' },
    { name: 'labelField', type: '`string | null`', default: '`null`', meaning: 'Field shown as the tile\'s name. Defaults to the type\'s display name.' },
    { name: 'subLabelField', type: '`string | CollectionColumn | null`', default: '`null`', meaning: 'The left of the metadata line. A resolved column renders it by type.' },
    { name: 'subLabel', type: '`(row) => string`', default: '—', meaning: 'The caller\'s own sub-label. Wins over `subLabelField`.' },
    { name: 'secondaryField', type: '`string | CollectionColumn | null`', default: '`null`', meaning: 'The right of the metadata line.' },
    { name: 'secondary', type: '`(row) => string`', default: '—', meaning: 'The caller\'s own text on the right. Wins over `secondaryField`.' },
    { name: 'showCode', type: '`boolean`', default: '`false`', meaning: 'Show the row\'s `code` beside the name when the two differ.' },
    { name: 'statuses', type: '`Record<string, StatusRecord> | null`', default: '`null`', meaning: 'Status rows by code. Read through the context when not given.' },
    { name: 'size', type: '`\'sm\' | \'md\' | \'lg\'`', default: '`\'md\'`', meaning: 'Tile size and column minimum: 160, 224 or 288 pixels.' },
    { name: 'selectable', type: '`boolean`', default: '`false`', meaning: 'Draws a checkbox on each tile.' },
    { name: 'isRowDisabled', type: '`(row) => boolean`', default: '—', meaning: 'True for a row the arrows skip and the selection refuses.' },
    { name: 'sort', type: '`SortSpec[]`', default: '—', meaning: 'The source\'s sort, two-way, so a SortPicker drops into `header`.' },
    { name: 'filters', type: '`FilterNode | WireGroup | null`', default: '—', meaning: 'The source\'s filter, two-way, so a FilterBar drops into `header`.' },
    { name: 'paging', type: '`\'pages\' | \'more\' | \'scroll\'`', default: '`\'scroll\'`', meaning: 'How the set is walked: a page number, a load-more row, or the scroller.' },
    { name: 'pageSizes', type: '`number[]`', default: '`[25, 50, 100]`', meaning: 'Rows per page offered in the footer. `pages` only.' },
    { name: 'maxHeight', type: '`string`', default: '`\'32rem\'`', meaning: 'Height of the scrolling body.' },
    { name: 'virtualizeAfter', type: '`number`', default: '`100`', meaning: 'Rows above which the grid draws only the tiles on screen.' },
    { name: 'emptyLabel', type: '`string`', default: '`\'No rows\'`', meaning: 'Shown when the read returned nothing.' },
    { name: 'errorLabel', type: '`string`', default: '—', meaning: 'Shown in place of what the failed read said.' },
    { name: 'density', type: '`\'compact\' | \'default\'`', default: '`\'default\'`', meaning: 'Compact halves the gap between tiles.' },
    { name: 'class / className', type: '`string`', default: '—', meaning: 'Merged after the widget\'s own classes.' },
  ],
  events: [
    { name: 'onSelectionChange', payload: '`EntityRef[]`', when: 'The selection changed.' },
    { name: 'onSelect', payload: '`EntityRow`', when: 'A tile was activated, by click or by Enter.' },
    { name: 'onSortChange', payload: '`SortSpec[]`', when: 'The source\'s sort changed.' },
    { name: 'onFiltersChange', payload: '`FilterNode | WireGroup | null`', when: 'The source\'s filter changed.' },
  ],
  slots: [
    { name: 'card', receives: '`{ row, id, index, selected, disabled, active }`', draws: 'Draws one grid cell. The grid keeps the cell\'s box, its tab stop and its keys.' },
    { name: 'header', receives: '—', draws: 'Region above the grid.' },
    { name: 'footer', receives: '—', draws: 'Region below the footer.' },
  ],
  keyboard: [
    { key: 'Tab', does: 'Moves into the grid, then out of it.' },
    { key: 'Left, Right', does: 'Moves the cursor one tile.' },
    { key: 'Up, Down', does: 'Moves the cursor one row of tiles.' },
    { key: 'Home, End', does: 'Moves to the first or the last tile.' },
    { key: 'Right, Down past the last tile', does: 'In `more` and `scroll`, asks for the next page. The cursor stays where it is until the tiles arrive, then lands on the first of them.' },
    { key: 'Space', does: 'Selects the tile, when the grid is selectable.' },
    { key: 'Enter', does: 'Emits the select event.' },
    { key: 'Enter in the page number', does: 'Goes to that page.' },
  ],
} satisfies PropsFile;
