import type { PropsFile } from './_types';

export default {
  extends: { name: 'picker-control', omit: ['slot', 'picker', 'label', 'multiple', 'keys', 'onSelect', 'labels', 'items', 'rowCount', 'chipKeys', 'chipsSlot', 'summary', 'max', 'chipRow', 'inline', 'tokenInput', 'inputPlaceholder', 'searchable', 'textValue', 'rowKey', 'inert', 'query', 'onQueryChange', 'onRemoveAt', 'onClear', 'anchored', 'loading', 'count', 'error', 'empty', 'hasMore', 'onLoadMore', 'clearLabel', 'triggerLabel', 'overflowLabel', 'itemToStringLabel', 'controlProps', 'chip', 'rows'] },
  props: [
    { name: 'entityTypes', type: '`string[]`', default: 'required', meaning: 'Types to search. Several make the picker polymorphic.' },
    { name: 'context', type: '`SgContext`', default: 'required', meaning: 'The widget context. Every read goes through it, so widgets on a page share one cache.' },
    { name: 'value', type: '`EntityRef | null`', default: '`null`', meaning: 'The chosen row. Two-way in Svelte.' },
    { name: 'labelField', type: '`string`', default: 'display-name chain', meaning: 'Field holding the row label.' },
    { name: 'searchFields', type: '`string[] | ((query) => string[])`', default: '`[]`', meaning: 'Fields matched on top of the display-name chain. A function is called with the query.' },
    { name: 'secondaryField', type: '`string | CollectionColumn | null`', default: '`null`', meaning: 'Field shown right-aligned, drawn by its data type. A resolved column renders it by type.' },
    { name: 'secondary', type: '`(row) => string`', default: '—', meaning: 'Right-aligned text of your own. Wins over `secondaryField`.' },
    { name: 'subLabelField', type: '`string | CollectionColumn | null`', default: '`null`', meaning: 'Field shown under the label, drawn by its data type: a status reads its display name.' },
    { name: 'subLabel', type: '`(row) => string`', default: 'the type, when several are searched', meaning: 'Computes the sub-label.' },
    { name: 'thumbnail', type: '`string | false`', default: '`\'image\'`', meaning: 'Field holding the thumbnail URL. `false` hides the leading slot.' },
    { name: 'roundThumbnail', type: '`boolean`', default: '`false`', meaning: 'Draws the thumbnail as a circle.' },
    { name: 'showCode', type: '`boolean`', default: '`false`', meaning: 'Shows the row\'s `code` beside the label when the two differ.' },
    { name: 'siteUrl', type: '`string`', default: 'the context\'s', meaning: 'The site the status sprite is served from, for a secondary that is a status.' },
    { name: 'fields', type: '`string[]`', default: '`[]`', meaning: 'Extra fields to request.' },
    { name: 'filters', type: '`FilterGroup | WireGroup | null`', default: '`null`', meaning: 'Pre-filter, merged into every search with `and`.' },
    { name: 'projectId', type: '`number`', default: '—', meaning: 'Scopes to one project.' },
    { name: 'exclude', type: '`EntityRef[]`', default: '`[]`', meaning: 'Rows kept out of the results.' },
    { name: 'minQueryLength', type: '`number`', default: '`0`', meaning: 'Under it the query carries no name condition.' },
    { name: 'pageSize', type: '`number`', default: '`20`', meaning: 'Rows a page, with a load more row under them.' },
    { name: 'placeholder', type: '`string`', default: '`\'Search for an entity\'`', meaning: 'Shown in the control while nothing is chosen.' },
    { name: 'searchPlaceholder', type: '`string`', default: '`\'Search…\'`', meaning: 'Shown in the query input once something is chosen.' },
    { name: 'emptyLabel', type: '`string`', default: '`\'No match\'`', meaning: 'Shown when a query matches nothing.' },
    { name: 'loadingLabel', type: '`string`', default: '`\'Loading…\'`', meaning: 'Names the skeletons a read stands behind, for a screen reader.' },
    { name: 'errorLabel', type: '`string`', default: '—', meaning: 'Shown in place of what the failed read said.' },
    { name: 'readonly', type: '`boolean`', default: '`false`', meaning: 'Keeps full contrast and drops the affordances.' },
    { name: 'invalid', type: '`boolean`', default: '`false`', meaning: 'Sets `aria-invalid` and the destructive ring.' },
    { name: 'clearable', type: '`boolean`', default: '`true`', meaning: 'Shows the clear control.' },
    { name: 'debounceMs', type: '`number`', default: '`250`', meaning: 'Wait after the last keystroke before searching.' },
    { name: 'class / className', type: '`string`', default: '—', meaning: 'Merged after the widget\'s own classes.' },
  ],
  events: [
    { name: 'onValueChange', payload: '`EntityRef | null`, `PickerRow | null`', when: 'A row was chosen, or the clear control was pressed.' },
    { name: 'onError', payload: '`Error`', when: 'A read failed. The list shows it inline as well.' },
    { name: 'onOpenChange', payload: '`boolean`', when: 'The popup opened or closed. Svelte also binds it with `bind:open`.' },
  ],
  keyboard: [
    { key: 'any text', does: 'Opens the list and searches the server.' },
    { key: '`Enter`, `Space`', does: 'On the chevron, opens the list.' },
    { key: '`Up`, `Down`', does: 'Moves the highlight through the rows and keeps it in view, including across a load more page. The last row holds it rather than wrapping.' },
    { key: '`Enter`', does: 'Chooses the highlighted row, or loads the next page on the load more row.' },
    { key: '`Backspace`', does: 'In an empty search box, clears the value.' },
    { key: '`Escape`', does: 'Closes the list and clears the query. On a closed picker it does nothing.' },
    { key: '`Tab`', does: 'Moves to the clear control, then the chevron, then out.' },
  ],
} satisfies PropsFile;
