import type { PropsFile } from './_types';

export default {
  extends: { name: 'collection-control' },
  props: [
    { name: 'columns', type: '`CollectionColumn[]`', default: 'required', meaning: 'Columns in display order, from `resolveColumns`. Two-way: hiding one writes the shorter list back.' },
    { name: 'statuses', type: '`Record<string, StatusRecord> | null`', default: '`null`', meaning: 'Status rows by code, for status cells.' },
    { name: 'context', type: '`SgContext`', default: '—', meaning: 'The widget context. Cells render with its preferences, a cell editor reads through it, and an entity cell links to the row\'s page when it carries a site.' },
    { name: 'projectId', type: '`number`', default: '—', meaning: 'The project the columns were resolved with. Scopes a status, list or entity cell editor.' },
    { name: 'precision', type: '`number`', default: '—', meaning: 'Decimals a float cell keeps.' },
    { name: 'symbol', type: '`string`', default: '`\'$\'`', meaning: 'Shown before the value in a currency cell.' },
    { name: 'density', type: '`\'compact\' | \'default\'`', default: '`\'default\'`', meaning: 'Compact halves the vertical cell padding and draws a cell chip and badge a step smaller.' },
    { name: 'selectable', type: '`boolean`', default: '`false`', meaning: 'Draws a checkbox column; a press on a row selects it, with Shift for a range.' },
    { name: 'onSelectAllMatching', type: '`() => void | Promise<void>`', default: '—', meaning: 'Offers every row the filter matches once every loaded row is selected and the set holds more. The host reads the set and writes the selection.' },
    { name: 'isRowDisabled', type: '`(row) => boolean`', default: '—', meaning: 'True for a row that cannot be selected or edited.' },
    { name: 'groupBy', type: '`string | null`', default: '`null`', meaning: 'Collapses rows under headers of a shared value at this path.' },
    { name: 'collapsed', type: '`string[] | CollapseState`', default: '`expandAll()`', meaning: 'Which group headers are shut, two-way. A bare id list is the open mode with those ids shut.' },
    { name: 'editable', type: '`boolean`', default: '`false`', meaning: 'Lets an editable cell open an editor.' },
    { name: 'editorFor', type: '`(dataType) => ComponentType<CellEditorProps> | null` / `(dataType) => Component<CellEditorProps> | null`', default: '—', meaning: 'The editor a cell opens, by data type. A type it does not answer for opens FieldEditor.' },
    { name: 'editorPlacement', type: '`\'inline\' | \'popover\'`', default: 'per data type', meaning: 'Where every cell editor opens. A column\'s own `editorPlacement` wins over it.' },
    { name: 'showCode', type: '`boolean`', default: '`false`', meaning: 'Show the programmatic field path beside the header\'s display name.' },
    { name: 'columnMenu', type: '`boolean`', default: '`false`', meaning: 'A menu on every header: sort, hide and pin left.' },
    { name: 'columnPicker', type: '`boolean`', default: '`false`', meaning: 'A Columns button in the toolbar: the user adds, removes and reorders the type\'s fields, kept in this browser. Needs `context`.' },
    { name: 'columnsKey', type: '`string`', default: 'one per entity type', meaning: 'The localStorage key the column choice is kept under.' },
    { name: 'paging', type: '`\'pages\' | \'more\' | \'scroll\'`', default: '`\'pages\'`', meaning: 'How the set is walked: a page number, a load-more row, or the scroller.' },
    { name: 'pageSizes', type: '`number[]`', default: '`[25, 50, 100]`', meaning: 'Rows per page offered in the footer. `pages` only.' },
    { name: 'maxHeight', type: '`string`', default: '`\'28rem\'`', meaning: 'Height of the scrolling body.' },
    { name: 'virtualizeAfter', type: '`number`', default: '`100`', meaning: 'Rows above which the body is virtualised.' },
    { name: 'emptyLabel', type: '`string`', default: '`\'No rows\'`', meaning: 'Shown when the read returned nothing.' },
    { name: 'errorLabel', type: '`string`', default: '—', meaning: 'Shown in place of what the failed read said.' },
    { name: 'size', type: '`\'sm\' | \'md\' | \'lg\'`', default: '`\'md\'`', meaning: 'Row text and header height: `text-xs`/`h-9`, `text-sm`/`h-10`, `text-base`/`h-11`.' },
    { name: 'class / className', type: '`string`', default: '—', meaning: 'Merged after the widget\'s own classes.' },
  ],
  events: [
    { name: 'onColumnsChange', payload: '`CollectionColumn[]`', when: 'A column was hidden from its header menu, or chosen in the column picker.' },
    { name: 'onSelectionChange', payload: '`EntityRef[]`', when: 'The selection changed.' },
    { name: 'onCollapsedChange', payload: '`CollapseState`', when: 'A group header was opened or shut.' },
    { name: 'onSortChange', payload: '`SortSpec[]`', when: 'The source\'s sort changed, from a header or from the prop.' },
    { name: 'onFiltersChange', payload: '`FilterNode | WireGroup | null`', when: 'The source\'s filter changed.' },
  ],
  slots: [
    { name: 'toolbarStart', receives: '—', draws: 'Left region of the toolbar above the table.' },
    { name: 'toolbarEnd', receives: '—', draws: 'Right region of the toolbar above the table.' },
    { name: 'row', receives: '`{ row, id, index, selected, disabled, columns }`', draws: 'Draws the cells of one row. The table keeps the row\'s box.' },
    { name: 'cell', receives: '`{ row, id, column, value, disabled }`', draws: 'Draws one cell\'s contents. Ignored where `row` is given.' },
    { name: 'groupHeader', receives: '`{ value, column, count, expanded, id }`', draws: 'Draws a group header\'s contents, after its chevron.' },
  ],
  keyboard: [
    { key: 'Tab', does: 'Moves through toolbar, header buttons, column menus, checkboxes, editable cells and the footer.' },
    { key: 'Enter, Space on a header', does: 'Sorts by that column, ascending, then descending, then unsorted.' },
    { key: 'Enter, Space on a column menu', does: 'Opens it; arrows walk it, Escape closes it.' },
    { key: 'Enter on an editable cell', does: 'Opens the editor.' },
    { key: 'Enter in an editor', does: 'Commits the value. In a textarea it adds a line, and Cmd or Ctrl with Enter commits.' },
    { key: 'Escape in an editor', does: 'Cancels and restores the value.' },
    { key: 'a press outside an editor', does: 'Commits the value.' },
    { key: 'Enter, Escape, Save, Cancel in a popover editor', does: 'The same: Enter and Save commit, Escape and Cancel restore.' },
    { key: 'Space on a checkbox or a cell', does: 'Toggles the row, or every loaded row from the header.' },
    { key: 'Shift+ArrowDown, Shift+ArrowUp in the body', does: 'Moves the cursor and carries the range from the anchor with it, selecting or clearing as the anchor went.' },
    { key: 'Cmd+A, Ctrl+A in the table', does: 'Selects every loaded row, keeping picks from other pages.' },
    { key: 'ArrowDown, ArrowUp in the body', does: 'Moves the cursor down or up the same column, over the rows it can land on.' },
    { key: 'ArrowDown on the last loaded row', does: 'In `more` and `scroll`, asks for the next page. The cursor stays where it is until the rows arrive, then lands on the first of them.' },
    { key: 'Enter in the page number', does: 'Goes to that page.' },
  ],
} satisfies PropsFile;
