import type { PropsFile } from './_types';

export default {
  props: [
    { name: 'context', type: '`SgContext`', default: 'required', meaning: 'The widget context. Every read goes through it, so widgets on a page share one cache.' },
    { name: 'rootPath', type: '`string`', default: 'required', meaning: 'Where the tree starts, `/Project/<id>`.' },
    { name: 'seedPath', type: '`string | string[] | null`', default: '`null`', meaning: 'Opens the tree down to this path, or to the last entry of an incremental path.' },
    { name: 'checkable', type: '`boolean`', default: '`false`', meaning: 'Draws a checkbox per node and reports the checked rows.' },
    { name: 'selectionMode', type: '`\'none\' | \'single\' | \'multiple\'`', default: '`\'single\'`', meaning: 'How many nodes may be selected at once.' },
    { name: 'selection', type: '`string[]`', default: 'the tree\'s own', meaning: 'Paths of the selected nodes, two-way. Unset, the tree keeps its own.' },
    { name: 'expanded', type: '`string[]`', default: '—', meaning: 'Paths of the open nodes, two-way. Setting it opens exactly those, reading whatever level is not loaded.' },
    { name: 'isRowDisabled', type: '`(node) => boolean`', default: '—', meaning: 'True for a node the arrows skip and the selection refuses.' },
    { name: 'searchable', type: '`boolean`', default: '`false`', meaning: 'Shows an input that searches the project and opens the tree onto the hits.' },
    { name: 'searchPlaceholder', type: '`string`', default: '`\'Search\'`', meaning: 'Placeholder and label of that input.' },
    { name: 'expandDepth', type: '`number`', default: '`3`', meaning: 'Levels a whole-branch expansion opens.' },
    { name: 'thumbnail', type: '`string | false`', default: '`false`', meaning: 'The image field to draw a thumbnail from.' },
    { name: 'labelField', type: '`string`', default: '—', meaning: 'Field shown as the label, in place of the tree\'s own.' },
    { name: 'subLabelField', type: '`string | CollectionColumn | null`', default: '`null`', meaning: 'Field shown under the label, drawn by its data type: a status reads its display name.' },
    { name: 'subLabel', type: '`(node) => string`', default: '—', meaning: 'Muted line under the label. Wins over `subLabelField`.' },
    { name: 'secondaryField', type: '`string | CollectionColumn | null`', default: '`null`', meaning: 'Right-aligned field, drawn by its data type. A resolved column renders it by type.' },
    { name: 'secondary', type: '`(node) => string`', default: '—', meaning: 'Right-aligned text. Wins over `secondaryField`.' },
    { name: 'showCode', type: '`boolean`', default: '`false`', meaning: 'Show the schema name beside the label on a node that stands for a type.' },
    { name: 'fields', type: '`string[]`', default: '—', meaning: 'Extra fields to request, so a caller\'s own sub-label or secondary can read them.' },
    { name: 'siteUrl', type: '`string`', default: 'the context\'s', meaning: 'The site the status sprite is served from.' },
    { name: 'label', type: '`string`', default: '`\'Project hierarchy\'`', meaning: 'Accessible name of the tree.' },
    { name: 'maxHeight', type: '`string`', default: '`\'24rem\'`', meaning: 'Height of the scrolling body.' },
    { name: 'emptyLabel', type: '`string`', default: '`\'No rows\'`', meaning: 'Shown when the root has no children.' },
    { name: 'noMatchLabel', type: '`string`', default: '`\'No match\'`', meaning: 'Shown when a search matched no row.' },
    { name: 'loadingLabel', type: '`string`', default: '`\'Loading…\'`', meaning: 'Names the skeletons a read stands behind, for a screen reader.' },
    { name: 'errorLabel', type: '`string`', default: '—', meaning: 'Shown in place of what the failed read said.' },
    { name: 'size', type: '`\'sm\' | \'md\' | \'lg\'`', default: '`\'md\'`', meaning: 'Row text, leading slot and glyphs, and the search input on the control ladder.' },
    { name: 'density', type: '`\'compact\' | \'default\'`', default: '`\'default\'`', meaning: 'Compact halves the vertical row padding and draws a row chip and badge a step smaller.' },
    { name: 'class / className', type: '`string`', default: '—', meaning: 'Merged after the widget\'s own classes.' },
  ],
  events: [
    { name: 'onSelect', payload: '`TreeNode`', when: 'A node with nothing under it was chosen.' },
    { name: 'onSelectionChange', payload: '`string[]`', when: 'The selected paths changed.' },
    { name: 'onExpandedChange', payload: '`string[]`', when: 'The open paths changed.' },
    { name: 'onCheckedChange', payload: '`EntityRef[]`', when: 'The checked set changed. Only nodes that stand for a row are reported.' },
    { name: 'onError', payload: '`Error`', when: 'A read failed.' },
  ],
  slots: [
    { name: 'row', receives: '`{ node, id, level, expanded, selected, disabled, match }`', draws: 'Draws a row\'s contents: everything after the chevron and the checkbox.' },
    { name: 'header', receives: '—', draws: 'Region above the search input.' },
    { name: 'footer', receives: '—', draws: 'Region below the tree.' },
  ],
  keyboard: [
    { key: 'Down', does: 'Moves to the next visible node.' },
    { key: 'Up', does: 'Moves to the previous visible node.' },
    { key: 'Right', does: 'Opens a closed branch, else moves to its first child.' },
    { key: 'Left', does: 'Closes an open branch, else moves to its parent.' },
    { key: 'Home', does: 'Moves to the first node.' },
    { key: 'End', does: 'Moves to the last visible node.' },
    { key: 'Space', does: 'Toggles the node\'s checkbox.' },
    { key: 'Enter', does: 'Selects the node.' },
    { key: '*', does: 'Opens every branch at the focus level, `expandDepth` levels deep.' },
    { key: 'Escape', does: 'In the search input, clears it.' },
    { key: 'a–z, 0–9', does: 'Moves to the next node whose label starts with what was typed. The same letter again walks the matches.' },
  ],
} satisfies PropsFile;
