import type { PropsFile } from './_types';

export default {
  props: [
    { name: 'context', type: '`SgContext`', default: 'required', meaning: 'The widget context. The schema is read through it, once per page.' },
    { name: 'entityType', type: '`string`', default: 'required', meaning: 'The type the path starts on.' },
    { name: 'value', type: '`string`', default: '`\'\'`', meaning: 'The dotted path. Empty when nothing is chosen.' },
    { name: 'onValueChange', type: '`(value: string) => void`', default: '—', meaning: 'Receives the new path, or the empty string on clear.' },
    { name: 'deepLinks', type: '`boolean`', default: '`false`', meaning: 'Allow descending through entity fields.' },
    { name: 'showCode', type: '`boolean`', default: '`false`', meaning: 'Show the programmatic name beside the display name in each row.' },
    { name: 'maxDepth', type: '`number`', default: '`2`', meaning: 'How many hops a path may take.' },
    { name: 'dataTypes', type: '`string | string[]`', default: '—', meaning: 'Data types a field must have to be selected.' },
    { name: 'validTypes', type: '`string[]`', default: '—', meaning: 'A field is selectable only if it links one of these.' },
    { name: 'exclude', type: '`string[]`', default: '—', meaning: 'Full dotted paths to drop.' },
    { name: 'hidePaths', type: '`string[]`', default: '—', meaning: 'Dotted prefixes to drop, along with everything beneath them.' },
    { name: 'filterableOnly', type: '`boolean`', default: '`false`', meaning: 'Drop the data types the API refuses in a filter.' },
    { name: 'extraFields', type: '`{ name, displayName? }[]`', default: '—', meaning: 'Synthetic entries offered at the root only, labelled `computed`.' },
    { name: 'filter', type: '`(field, path) => boolean`', default: '—', meaning: 'Your own visibility test over the schema and the candidate\'s full path.' },
    { name: 'closeOnSelect', type: '`boolean`', default: '`true`', meaning: 'Off keeps the popover open for the next pick.' },
    { name: 'placeholder', type: '`string`', default: '`\'Select a field\'`', meaning: 'Shown while nothing is chosen.' },
    { name: 'searchPlaceholder', type: '`string`', default: '`\'Search fields…\'`', meaning: 'Shown in the search box.' },
    { name: 'emptyLabel', type: '`string`', default: '`\'No match\'`', meaning: 'Shown when the search matches nothing.' },
    { name: 'loadingLabel', type: '`string`', default: '`\'Loading…\'`', meaning: 'Names the skeletons a read stands behind, for a screen reader.' },
    { name: 'errorLabel', type: '`string`', default: '—', meaning: 'Shown in place of what the failed read said.' },
    { name: 'clearable', type: '`boolean`', default: '`true`', meaning: 'Show the clear control once a field is chosen.' },
    { name: 'readonly', type: '`boolean`', default: '`false`', meaning: 'Keeps full contrast and removes the chevron and the clear control.' },
    { name: 'disabled', type: '`boolean`', default: '`false`' },
    { name: 'invalid', type: '`boolean`', default: '`false`', meaning: 'Applies the invalid ring and `aria-invalid`.' },
    { name: 'size', type: '`\'sm\' | \'md\' | \'lg\'`', default: '`\'md\'`' },
    { name: 'open', type: '`boolean`', default: '`false`', meaning: 'Whether the popover is showing. Two-way in Svelte.' },
    { name: 'className / class', type: '`string`', default: '—', meaning: 'Merged after the widget\'s own classes.' },
  ],
  events: [
    { name: 'onValueChange', payload: '`string`', when: 'A field is chosen, or the clear control is pressed, which sends the empty string.' },
    { name: 'onOpenChange', payload: '`boolean`', when: 'The popover opened or closed. Svelte also binds it with `bind:open`.' },
  ],
  keyboard: [
    { key: '`Enter`, `Space`', does: 'On the closed control, opens it.' },
    { key: '`Down`, `Up`', does: 'Move the cursor through the rows.' },
    { key: '`Right`', does: 'Descend into the highlighted field, or pick the highlighted target type.' },
    { key: '`Left`', does: 'Go back one level, or cancel the choice of target type.' },
    { key: '`Enter`', does: 'Choose the highlighted field. On a field that can only be descended into, descends.' },
    { key: '`Backspace`', does: 'In an empty search box, clears the value.' },
    { key: '`Escape`', does: 'Close, keeping the value.' },
  ],
} satisfies PropsFile;
