import type { PropsFile } from './_types';

export default {
  props: [
    { name: 'errorMessage', type: '`(message: string) => ReactNode`', default: '—', meaning: 'Draws the line under the control.' },
    { name: 'value', type: '`unknown`', default: '`null`', meaning: 'The raw attribute value, as the API returned it. Two-way in Svelte.' },
    { name: 'onValueChange', type: '`(value: unknown) => void`', default: '—', meaning: 'Called when the editor commits.' },
    { name: 'dataType', type: '`string`', default: 'the schema\'s, then `\'text\'`', meaning: 'Picks the editor.' },
    { name: 'field', type: '`FieldSchema | null`', default: '`null`', meaning: 'The field schema.' },
    { name: 'mode', type: '`\'display\' | \'edit\'`', default: '`\'display\'`', meaning: 'Which half is showing. Two-way in Svelte, controlled in React.' },
    { name: 'onModeChange', type: '`(mode) => void`', default: '—', meaning: 'Called when the toggle moves.' },
    { name: 'editable', type: '`boolean`', default: '`false`', meaning: 'Turns the display half into a control that opens the editor.' },
    { name: 'editorPlacement', type: '`\'inline\' | \'popover\'`', default: '`\'inline\'`', meaning: 'Where the editor opens: in place of the value, or in a popover anchored to it.' },
    { name: 'statuses', type: '`Record<string, StatusRecord> | null`', default: '`null`', meaning: 'Status rows by code, for the display half.' },
    { name: 'context', type: '`SgContext`', default: '—', meaning: 'The widget context: the site preferences, and what the display half reads.' },
    { name: 'hoursPerDay', type: '`number`', default: 'the context\'s', meaning: 'The site\'s working day, for durations.' },
    { name: 'locale', type: '`string`', default: 'the context\'s, then the runtime\'s', meaning: 'Passed to the display half.' },
    { name: 'timeZone', type: '`string`', default: 'the context\'s, then the runtime\'s', meaning: 'Zone a typed wall-clock time is read in.' },
    { name: 'frameRate', type: '`number`', default: 'the context\'s', meaning: 'Frames a second, for timecodes.' },
    { name: 'precision', type: '`number`', default: '—', meaning: 'Decimals on a float.' },
    { name: 'symbol', type: '`string`', default: '`\'$\'`', meaning: 'Shown before a currency value.' },
    { name: 'projectId', type: '`number`', default: '—', meaning: 'Removes a list field\'s hidden values, and scopes a status or entity picker.' },
    { name: 'multiline', type: '`boolean`', default: '`true` in a popover', meaning: 'A textarea on a text field. In a textarea Enter adds a line and Cmd or Ctrl with Enter commits.' },
    { name: 'size', type: '`\'sm\' | \'md\' | \'lg\'`', default: '`\'md\'`', meaning: 'Control height.' },
    { name: 'disabled', type: '`boolean`', default: '`false`' },
    { name: 'readonly', type: '`boolean`', default: '`false`' },
    { name: 'invalid', type: '`boolean`', default: '`false`', meaning: 'Forced invalid state.' },
    { name: 'error', type: '`string | null`', default: '`null`', meaning: 'A message from the caller.' },
    { name: 'onErrorChange', type: '`(error: string | null) => void`', default: '—', meaning: 'Called when the parse error appears or clears.' },
    { name: 'placeholder', type: '`string`', default: '—' },
    { name: 'emptyLabel', type: '`string`', default: '`\'empty\'`', meaning: 'Marker the display half shows for an unset value.' },
    { name: 'class / className', type: '`string`', default: '—', meaning: 'Merged after the widget\'s own classes.' },
  ],
  keyboard: [
    { key: '`Enter`', does: 'Opens the editor from the display half; commits and closes it from the edit half.' },
    { key: '`Space`', does: 'Opens the editor from the display half.' },
    { key: '`Escape`', does: 'Cancels the edit and returns to the display half.' },
    { key: '`Tab`', does: 'Commits and returns to the display half, unless focus stays inside a popup the editor opened.' },
    { key: 'a press outside', does: 'Commits and returns to the display half.' },
    { key: '`Escape`, `Enter` in a popover', does: 'Cancels and commits as they do in place; Save and Cancel do the same with the pointer.' },
  ],
} satisfies PropsFile;
