import type { PropsFile } from './_types';

export default {
  extends: { name: 'collection-control' },
  props: [
    { name: 'source', type: '`EntitySource`', default: '—', meaning: 'The rows and the order behind them.' },
    { name: 'groupBy', type: '`CollectionColumn`', default: '—', meaning: 'Column the rows are grouped on. The source is sorted on it. Not read with `groupKey`. One of the two is required.' },
    { name: 'groupKey', type: '`(row) => unknown`', default: '—', meaning: 'The value a row groups under, derived from the row and compared by its JSON text. The source\'s sort is left as the caller set it.' },
    { name: 'groupLabel', type: '`(value) => string`', default: '—', meaning: 'The header\'s text for a derived key; not read with `groupBy`. Without it the key reads as its own display name.' },
    { name: 'thumbnail', type: '`string | false`', default: '`false`', meaning: 'Field holding the thumbnail URL.' },
    { name: 'labelField', type: '`string | null`', default: '`null`', meaning: 'Field shown as the row\'s label. Defaults to the type\'s display name.' },
    { name: 'subLabelField', type: '`string | CollectionColumn | null`', default: '`null`', meaning: 'The muted line under the label. A resolved column renders it by type.' },
    { name: 'subLabel', type: '`(row) => string`', default: '—', meaning: 'The caller\'s own sub-label. Wins over `subLabelField`.' },
    { name: 'secondaryField', type: '`string | CollectionColumn | null`', default: '`null`', meaning: 'The right-aligned value at the end of the row.' },
    { name: 'secondary', type: '`(row) => string`', default: '—', meaning: 'The caller\'s own right-aligned text. Wins over `secondaryField`.' },
    { name: 'showCode', type: '`boolean`', default: '`false`', meaning: 'Show the row\'s `code` beside the label when the two differ.' },
    { name: 'details', type: '`CollectionColumn[]`', default: '`[]`', meaning: 'Extra values drawn under the label. The source must already read their paths.' },
    { name: 'statuses', type: '`Record<string, StatusRecord> | null`', default: '`null`', meaning: 'Status rows by code.' },
    { name: 'context', type: '`SgContext`', default: '—', meaning: 'The widget context. Values render with its preferences, and an entity value links to the row\'s page when it carries a site.' },
    { name: 'density', type: '`\'compact\' | \'default\'`', default: '`\'default\'`', meaning: 'Compact halves the vertical row padding and draws a row chip and badge a step smaller.' },
    { name: 'selectable', type: '`boolean`', default: '`false`', meaning: 'Draws a checkbox on each row.' },
    { name: 'isRowDisabled', type: '`(row) => boolean`', default: '—', meaning: 'True for a row that cannot be selected or reached by Tab.' },
    { name: 'collapsed', type: '`string[] | CollapseState`', default: '`expandAll()`', meaning: 'Which groups are shut, two-way. A bare key list is the open mode with those keys shut.' },
    { name: 'sort', type: '`SortSpec[]`', default: '—', meaning: 'The source\'s sort, two-way, so a SortPicker drops into `header`.' },
    { name: 'filters', type: '`FilterNode | WireGroup | null`', default: '—', meaning: 'The source\'s filter, two-way, so a FilterBar drops into `header`.' },
    { name: 'paging', type: '`\'pages\' | \'more\' | \'scroll\'`', default: '`\'more\'`', meaning: 'How the set is walked: a page number, a load-more row, or the scroller.' },
    { name: 'pageSizes', type: '`number[]`', default: '`[25, 50, 100]`', meaning: 'Rows per page offered in the footer. `pages` only.' },
    { name: 'maxHeight', type: '`string`', default: '`\'28rem\'`', meaning: 'Height of the scrolling body.' },
    { name: 'virtualizeAfter', type: '`number`', default: '`100`', meaning: 'Rows and headers above which the list draws only the lines on screen.' },
    { name: 'emptyLabel', type: '`string`', default: '`\'No rows\'`', meaning: 'Shown when the read returned nothing.' },
    { name: 'errorLabel', type: '`string`', default: '—', meaning: 'Shown in place of what the failed read said.' },
    { name: 'size', type: '`\'sm\' | \'md\' | \'lg\'`', default: '`\'md\'`', meaning: 'Row text and thumbnail. A compact row takes the step below.' },
    { name: 'class / className', type: '`string`', default: '—', meaning: 'Merged after the widget\'s own classes.' },
  ],
  events: [
    { name: 'onSelectionChange', payload: '`EntityRef[]`', when: 'The selection changed.' },
    { name: 'onSelect', payload: '`EntityRow`', when: 'A row was activated, when `selectable` is off.' },
    { name: 'onCollapsedChange', payload: '`CollapseState`', when: 'A group was opened or shut.' },
    { name: 'onSortChange', payload: '`SortSpec[]`', when: 'The source\'s sort changed.' },
    { name: 'onFiltersChange', payload: '`FilterNode | WireGroup | null`', when: 'The source\'s filter changed.' },
  ],
  slots: [
    { name: 'leading', receives: '`EntityRow`', draws: 'Fixed-size slot at the start of the row, when `thumbnail` is not the one wanted: an avatar, a status glyph.' },
    { name: 'row', receives: '`{ row, id, index, selected, disabled }`', draws: 'Draws a row\'s contents. The list keeps the row\'s box.' },
    { name: 'groupHeader', receives: '`{ value, column, count, collapsed, id }`', draws: 'Draws a group header\'s contents, after its chevron. `column` is `null` for a derived key.' },
    { name: 'header', receives: '—', draws: 'Region above the list.' },
    { name: 'footer', receives: '—', draws: 'Region below the footer.' },
  ],
  keyboard: [
    { key: 'Tab', does: 'Moves through group headers, checkboxes, rows and the footer.' },
    { key: 'Enter, Space on a header', does: 'Collapses or expands the group.' },
    { key: 'Enter, Space on a row', does: 'Selects it, or emits the select event.' },
    { key: 'ArrowDown, ArrowUp on a row', does: 'Moves the cursor one row.' },
    { key: 'ArrowDown on the last loaded row', does: 'In `more` and `scroll`, asks for the next page. The cursor stays where it is until the rows arrive, then lands on the first of them.' },
    { key: 'Enter in the page number', does: 'Goes to that page.' },
  ],
} satisfies PropsFile;
