import type { PropsFile } from './_types';

export default {
  props: [
    { name: 'slot', type: '`string`', default: '—', meaning: 'The `data-slot` prefix every part of this picker carries.' },
    { name: 'picker', type: '`string`', default: '—', meaning: 'The `data-picker` the popup carries.' },
    { name: 'multiple', type: '`boolean`', default: '`false`', meaning: 'Several keys may be chosen at once.' },
    { name: 'keys', type: '`string[]`', default: '—', meaning: 'The chosen keys, in order. A single picker passes none or one.' },
    { name: 'onSelect', type: '`(keys: string[]) => void`', default: '—', meaning: 'The keys the primitive settled on. The load-more row never reaches it.' },
    { name: 'labels', type: '`string[]`', default: '—', meaning: 'One label per chosen key. The summary, the title and the measured row read it.' },
    { name: 'items', type: '`string[]`', default: '—', meaning: 'React: the item keys the list offers, in order.' , only: 'react' },
    { name: 'rowCount', type: '`number`', default: '`0`', meaning: 'Svelte: the rows on show, so a changed list follows the highlight.' , only: 'svelte' },
    { name: 'chipKeys', type: '`string[]`', default: 'index and label', meaning: 'Svelte: a stable key per chip, so a removal does not redraw the row.' , only: 'svelte' },
    { name: 'chipsSlot', type: '`string`', default: '`<slot>-chips`', meaning: 'The `data-slot` of the chip row.' },
    { name: 'summary', type: '`\'chips\' | \'ellipsis\' | \'count\'`', default: '`\'chips\'`', meaning: 'What the control shows for the selection.' },
    { name: 'max', type: '`number`', default: '`0`', meaning: 'Chips drawn before the rest becomes `+n`. `0` fits what the row can.' },
    { name: 'chipRow', type: '`boolean`', default: '`false`', meaning: 'The value is a measured row of chips rather than one chip.' },
    { name: 'inline', type: '`boolean`', default: '`true`', meaning: 'The control holds the caret. A summary control keeps it in the popup.' },
    { name: 'tokenInput', type: '`boolean`', default: '`true`', meaning: 'The caret gives its room to the chips.' },
    { name: 'inputPlaceholder', type: '`string`', default: '—', meaning: 'What the caret shows.' },
    { name: 'searchable', type: '`boolean`', default: '`true`', meaning: 'A summary control keeps a search row. A fixed set has nothing to search.' },
    { name: 'textValue', type: '`boolean`', default: '`false`', meaning: 'The filled value is plain text, so the control keeps the reading inset in both states.' },
    { name: 'rowKey', type: '`string`', default: 'size, summary and labels', meaning: 'What the chips look like, so a change re-measures the row.' },
    { name: 'size', type: '`\'sm\' | \'md\' | \'lg\'`', default: '`\'md\'`', meaning: 'Control height: 7, 8 and 9.' },
    { name: 'disabled', type: '`boolean`', default: '`false`' },
    { name: 'inert', type: '`boolean`', default: '`disabled`', meaning: 'The primitive takes no input. Wider than disabled: a loading picker is inert too.' },
    { name: 'readonly', type: '`boolean`', default: '`false`' },
    { name: 'invalid', type: '`boolean`', default: '`false`' },
    { name: 'clearable', type: '`boolean`', default: '`true`', meaning: 'The clear control is drawn once something is chosen.' },
    { name: 'placeholder', type: '`string`', default: '`\'\'`' },
    { name: 'label', type: '`string`', default: 'the placeholder, then `triggerLabel`', meaning: "The combobox's accessible name, for a control whose placeholder is empty." },
    { name: 'searchPlaceholder', type: '`string`', default: '`\'Search…\'`' },
    { name: 'open', type: '`boolean`', default: '`false`', meaning: 'Whether the popup is showing. Two-way in Svelte.' },
    { name: 'onOpenChange', type: '`(open: boolean) => void`', default: '—' },
    { name: 'query', type: '`string`', default: '`\'\'`', meaning: 'What the caret holds. Two-way in Svelte.' },
    { name: 'onQueryChange', type: '`(query: string) => void`', default: '—', meaning: 'React: called when the caret changes.' , only: 'react' },
    { name: 'onRemoveAt', type: '`(index: number) => void`', default: '—', meaning: 'Remove the chip at `index`. Backspace walks the row through it.' },
    { name: 'onClear', type: '`() => void`', default: '—' },
    { name: 'anchored', type: '`boolean`', default: '`false`', meaning: 'The popup is as wide as the control it hangs off.' },
    { name: 'loading', type: '`boolean`', default: '`false`', meaning: 'Skeleton rows in place of the list.' },
    { name: 'count', type: '`number`', default: '`0`', meaning: 'Svelte: rows the list offers, which is what the live region counts.', only: 'svelte' },
    { name: 'error', type: '`string | null`', default: '`null`', meaning: 'The error line in place of the list.' },
    { name: 'empty', type: '`boolean`', default: '`false`', meaning: 'The empty line in place of the list.' },
    { name: 'emptyLabel', type: '`string`', default: '`\'No match\'`' },
    { name: 'loadingLabel', type: '`string`', default: '`\'Loading…\'`', meaning: 'The accessible name of the skeletons.' },
    { name: 'errorLabel', type: '`string`', default: 'what the read said', meaning: 'Shown in place of the failed read\'s own message.' },
    { name: 'hasMore', type: '`boolean`', default: '`false`', meaning: 'A further page is there to be read, and the load-more row is drawn.' },
    { name: 'onLoadMore', type: '`() => void`', default: '—', meaning: 'Called by a press on the load-more row.' },
    { name: 'clearLabel', type: '`string`', default: '`\'Clear the selection\'`' },
    { name: 'triggerLabel', type: '`string`', default: '`\'Show the options\'`' },
    { name: 'overflowLabel', type: '`string`', default: '`\'Show all n selected\'`', meaning: 'The accessible name of the `+n` pill.' },
    { name: 'itemToStringLabel', type: '`(value: string) => string`', default: '—', meaning: 'React: what the primitive writes into the input for an item.' , only: 'react' },
    { name: 'controlProps', type: '`Record<string, unknown>`', default: '—', meaning: 'Attributes the control carries on top of the shared ones.' },
  ],
  slots: [
    { name: 'chip', react: 'renderChip', receives: 'the chip\'s index, whether the caret is on it, whether the row hides it', draws: 'One chip of the value. The chip under the caret wears the focus ring; a hidden one keeps its width.' },
    { name: 'rows', react: 'renderItem', receives: 'nothing in Svelte, the item key in React', draws: 'The rows of the list, as items of the primitive.' },
  ],
  keyboard: [
    { key: '`ArrowDown` / `ArrowUp`', does: 'Moves the highlight, and the list scrolls it into view.' },
    { key: '`Enter`', does: 'Takes the highlighted row. A multi picker keeps the popup open.' },
    { key: '`Escape`', does: 'Closes the popup and clears the query. On a closed picker it does nothing.' },
    { key: '`Backspace`', does: 'In an empty query: takes the caret to the last chip of a multi picker; clears a single one.' },
    { key: '`ArrowLeft` / `ArrowRight`', does: 'On a chip, walks the row. `ArrowRight` past the last chip returns to the input.' },
    { key: '`Delete`', does: 'On a chip, removes it and leaves the caret on its neighbour.' },
    { key: '`Tab`', does: 'Leaves the control.' },
  ],
} satisfies PropsFile;
